trigger:
  - develop
  - qa

parameters:
- name: stages
  type: object
  default:
    - name: 'Develop'
      group: 'frontend-vars-Develop'
      branch: 'develop'
    # - name: 'Qa'
    #   group: 'frontend-vars-Qa'
    #   branch: 'qa'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - ${{ each stage in parameters.stages }}:
    - stage: ${{ stage.name }}
      variables:
      - group: ${{ stage.group }}
      dependsOn: []
      condition: and(succeeded(), eq(variables['build.SourceBranchName'], '${{ stage.branch }}'))
      jobs:
      - job: build_to_${{ stage.name }}
        continueOnError: false
        steps:
        - script: |
            echo VITE_APP_API_URL=$(VITE_APP_API_URL)  >> .env
            echo VITE_APP_CLIENT_ID=$(VITE_APP_CLIENT_ID)  >> .env
            echo VITE_APP_REDIRECT_URI=$(VITE_APP_REDIRECT_URI)  >> .env
            echo VITE_APP_KNOWN_AUTHORITY=$(VITE_APP_KNOWN_AUTHORITY)  >> .env
            echo VITE_APP_AUTHORITY=$(VITE_APP_AUTHORITY)  >> .env
            cat .env
          displayName: "add .env ${{ stage.name }}"
        
        - script: yarn
          displayName: Installing dependencies using Yarn

        - script: yarn build
          displayName: Build application

        - script: |
            echo { "script": "serve", "env": { "PM2_SERVE_SPA": "true", "PM2_SERVE_HOMEPAGE": "/index.html" } } >> dist/process.json
          displayName: "add process.json"

        - task: AzureStaticWebApp@0
          inputs:
            app_location: '/dist'
            api_location: ''
            output_location: ''
            azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
 